### PR TITLE
update mpi config

### PR DESCRIPTION
**Pull request by CyrilleBonamy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CyrilleBonamy** [comment]
@conda-forge-admin, please rerender

**Comment by paugier** [comment]
Maybe `skip: true  # [win and mpi]`?

**Comment by ashwinvis** [comment]
@CyrilleBonamy So now we have to specify build number while installing?

**Comment by paugier** [comment]
@ashwinvis I guess that there is a priority for the larger build number so users don't need to specify it.

**Comment by CyrilleBonamy** [comment]
it is explained at the bottom of this section : https://conda-forge.org/docs/maintainer/knowledge_base.html#including-a-no-mpi-build

**Pull request merged**
